#!/usr/bin/env python3
"""
pipeline/download_fonts.py
Downloads Google Fonts (DM Serif Display, DM Sans, Heebo) to docs/assets/fonts/
and generates a self-hosted fonts.css.

Run once after cloning the repo, or whenever you want to refresh fonts:
    python pipeline/download_fonts.py

Output:
    docs/assets/fonts/*.woff2
    docs/assets/fonts/fonts.css
"""

import os
import sys
import urllib.request
import urllib.error
import re

FONTS_DIR = os.path.join("docs", "assets", "fonts")
FONTS_CSS = os.path.join(FONTS_DIR, "fonts.css")

# Google Fonts API URLs — one per font family, requesting woff2
# We use a modern Chrome UA to get woff2 format (smaller, universal support)
CHROME_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/122.0.0.0 Safari/537.36"
)

FONT_REQUESTS = [
    (
        "DM Serif Display",
        "https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&display=swap",
    ),
    (
        "DM Sans",
        "https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;1,9..40,400&display=swap",
    ),
    (
        "Heebo",
        "https://fonts.googleapis.com/css2?family=Heebo:wght@300;400;500;600;700&display=swap",
    ),
]


def fetch_url(url, headers=None):
    req = urllib.request.Request(url, headers=headers or {})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read()


def fetch_text(url, headers=None):
    return fetch_url(url, headers).decode("utf-8")


def safe_filename(url):
    """Extract a safe filename from a font URL."""
    # e.g. https://fonts.gstatic.com/s/dmsans/v15/rP2Yp2ywxg089UriI5-g4vlH9VoD8Cmcqbu6-K6z9mXgjU0.woff2
    name = url.split("/")[-1].split("?")[0]
    return name if name.endswith(".woff2") else name + ".woff2"


def download_fonts():
    os.makedirs(FONTS_DIR, exist_ok=True)

    all_face_rules = []

    for family_name, api_url in FONT_REQUESTS:
        print(f"Fetching CSS for: {family_name}")
        try:
            css = fetch_text(api_url, headers={"User-Agent": CHROME_UA})
        except Exception as e:
            print(f"  ERROR fetching CSS: {e}", file=sys.stderr)
            sys.exit(1)

        # Extract all @font-face blocks
        face_blocks = re.findall(r"@font-face\s*\{[^}]+\}", css)
        print(f"  Found {len(face_blocks)} @font-face blocks")

        for block in face_blocks:
            # Get woff2 URL
            woff2_match = re.search(r"url\((https://fonts\.gstatic\.com/[^\)]+\.woff2)\)", block)
            if not woff2_match:
                continue
            remote_url = woff2_match.group(1)
            local_name = safe_filename(remote_url)
            local_path = os.path.join(FONTS_DIR, local_name)

            if os.path.exists(local_path):
                print(f"  ✓ Already exists: {local_name}")
            else:
                print(f"  ↓ Downloading: {local_name}")
                try:
                    data = fetch_url(remote_url)
                    with open(local_path, "wb") as f:
                        f.write(data)
                    print(f"    {len(data) // 1024} KB")
                except Exception as e:
                    print(f"  ERROR: {e}", file=sys.stderr)
                    sys.exit(1)

            # Rewrite the url() in the block to use local relative path
            local_rel = local_name  # relative to fonts.css location
            new_block = block.replace(remote_url, local_rel)
            all_face_rules.append(new_block)

    # Write combined fonts.css
    fonts_css_content = (
        "/* Self-hosted fonts — generated by pipeline/download_fonts.py */\n"
        "/* Do not edit manually */\n\n"
    ) + "\n\n".join(all_face_rules) + "\n"

    with open(FONTS_CSS, "w", encoding="utf-8") as f:
        f.write(fonts_css_content)

    woff2_count = len([f for f in os.listdir(FONTS_DIR) if f.endswith(".woff2")])
    print(f"\n✅ Done: {woff2_count} font files + fonts.css written to {FONTS_DIR}/")
    print("   Update render.py to use local fonts (already handled if you're using current version).")


if __name__ == "__main__":
    download_fonts()
